# Generated by Django 3.2 on 2023-04-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.FileField(default='media/djangorest.png', upload_to=''),
        ),
    ]
