# Generated by Django 3.2 on 2023-04-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_room_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
