# Generated by Django 3.2 on 2023-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_message_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, default='upvote.png', null=True, upload_to='images/'),
        ),
    ]
