# Generated by Django 3.2 on 2023-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_message_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, default='images/upvote.png', null=True, upload_to='images/'),
        ),
    ]
