# Generated by Django 4.2 on 2023-04-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_pizza_topping_restaurant_pizza_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Restaurant Name', max_length=50),
        ),
    ]
