# Generated by Django 4.2 on 2023-04-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_restaurant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='origin',
            field=models.CharField(default='Italy', max_length=50),
        ),
    ]
